---
title: "Advanced examples"
abstract: >
  This vignette assumes you are familiar with set operations from the basic vignette.
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('BaseSet')`"
output:
  BiocStyle::html_document:
    fig_caption: true
    code_folding: show
    self_contained: yes
    toc_float:
      
      collapsed: true
      toc_depth: 3
author:
- name: Lluís Revilla
  affiliation: 
    - August Pi i Sunyer Biomedical Research Institute (IDIBAPS); Liver Unit, Hospital Clinic
  email: lluis.revilla@gmail.com
vignette: >
  %\VignetteIndexEntry{Advanced examples}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
To show compatibility with tidy workflows we will use magrittr pipe operator
```{r setup}
library("dplyr")
library("BaseSet")
```
We can create a tidySet with some sets being the intersection and the union of others:
```{r}
relations <- data.frame(sets = c(rep("A", 5), "B"),
                        elements = letters[seq_len(6)],
                        fuzzy = runif(6))
sample_set <- tidySet(relations) %>% 
  union(c("A", "B"), "C", keep = TRUE) %>% 
  intersection(c("B", "C"), "D", keep = TRUE)

# Number of elements per set
sample_set %>% 
  relations() %>% 
  group_by(sets) %>% 
  count()

# size of the sets and probability
sample_set %>% 
  set_size()
```



# Session info {.unnumbered}

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
